inputs:
  linkedin_csv: ./data/linkedin.csv
  gmail_csv: ./data/gmail.csv
  mac_vcf: ./data/mac.vcf
outputs:
  dir: ./output
normalization:
  default_phone_country: US
  keep_generational_suffixes:
  - jr
  - sr
  - ii
  - iii
  - iv
  - v
  - vi
  strip_professional_suffixes: true
  professional_suffixes:
  - phd
  - pmp
  - csm
  - spc6
  - ccim
  - phr
  - shrm
  - shrmcp
  - cp
  - mba
  - cissp
  - crisc
  - cscp
  - cams
  - cpa
  - cfa
  - pe
  - cisa
  - cism
  - cfe
  - cma
  - ceh
  - itil
  - sixsigma
  - leansixsigma
  - esq
  - jd
  - ms
  - rdn
  - ld
  - mpa
  - ise
  - md
  - mph
  name_prefixes:
  - dr
  - mr
  - mrs
  - ms
  - miss
  - prof
  - sir
  - madam
dedupe:
  enable_nickname_equivalence: true
  bucket_by_last_name: true
  first_name_similarity_threshold: 0.88
  merge_score_threshold: 1.2
  relaxed_merge_threshold: 0.6
  require_corroborator: false
validation:
  email_syntax_check: true
  email_dns_mx_check: true
  phone_strict_validation: true
  address_us_parse: false
quality:
  email_full_score: 40
  email_partial_score: 20
  phone_full_score: 30
  phone_partial_score: 15
  address_any_score: 30
tagging:
  prior_companies:
  - gridgain
  - red hat
  - tetrate
  - redhat
  - oracle
  - teamlogic
  - teamlogic it
  prior_domains:
  - gridgain.com
  - redhat.com
  - tetrate.io
  - oracle.com
  - teamlogicit.com
  local_cities:
  - braintree
  - quincy
  - weymouth
  - dedham
  - milton
  - hingham
logging:
  level: INFO
